spring:
  datasource:
    url: jdbc:mysql://${DB_ENDPOINT}:3306/dangeek
    username: ${DB_MASTER_USERNAME}
    password: ${DB_MASTER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

---
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
jwt:
  secret: "145612345sfdgsadgasg3w4tg34"
---
spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
    web:
      resources:
        add-mappings: false

univ:
  key: ${UNIV_KEY}
