server:
  port: 443
  ssl:
    enabled: true
    key-store: ${KEY_STORE}/keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    security.require-ssl: true
#server:
#port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_ENDPOINT}:3306/dangeek
    username: ${DB_MASTER_USERNAME}
    password: ${DB_MASTER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

---
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
jwt:
  secret: ${JWT_SECRET}
---
spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
    web:
      resources:
        add-mappings: false

univ:
  key: ${UNIV_KEY}
---
cloud:
  aws:
    s3:
      bucket: wonoong
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}